/*
 * Open the link below for a complete description of the available fields from shopify  :
 * https://help.shopify.com/en/manual/products/import-export/using-csv#description-of-the-product-csv-file
 *
 * /!\ Shopify can add/remove or change the name of the fields over time.
 *     If some fields are obsolete, shopify will warn you when importing the CSV in your store.
 *     In this case, you'll need to update this file accordingly with the help the link above.
 *
 * /!\ Please note that the 'Option[number] Name' and 'Option[value] Value' fields are generated by the script.
 *     Don't set them yourself!
 *
 * AVAILABLE FIELDS FOR @productOptions :
 * 'Body (HTML)'
 * 'Vendor'
 * 'Product category'
 * 'Product Type'
 * 'Tags'
 * 'Published'
 * 'Image Src'
 * 'Image Position'
 * 'Image Alt Text'
 * 'Gift Card'
 * 'SEO Title'
 * 'SEO Description'
 * 'Google Shopping / Google Product Category'
 * 'Google Shopping / Gender'
 * 'Google Shopping / Age Group'
 * 'Google Shopping / MPN'
 * 'Google Shopping / AdWords Grouping'
 * 'Google Shopping / AdWords Labels'
 * 'Google Shopping / Condition'
 * 'Google Shopping / Custom Product'
 * 'Google Shopping / Custom Label 0'
 * 'Google Shopping / Custom Label 1'
 * 'Google Shopping / Custom Label 2'
 * 'Google Shopping / Custom Label 3'
 * 'Google Shopping / Custom Label 4'
 * 'Status'
 *
 *
 * AVAILABLE FIELDS FOR @variantsOptions :
 * 'Variant SKU'
 * 'Variant Grams'
 * 'Variant Inventory Tracker'
 * 'Variant Inventory Qty'
 * 'Variant Inventory Policy'
 * 'Variant Fulfillment Service'
 * 'Variant Price'
 * 'Variant Compare At Price'
 * 'Variant Requires Shipping'
 * 'Variant Taxable'
 * 'Variant Barcode'
 * 'Variant Image'
 * 'Variant Weight Unit'
 * 'Variant Tax Code'
 * 'Cost per item'
 *
 */

// CONFIG START HERE
const CONFIG = {
  // Common options for all products.
  // These options will be added by default to all products.
  // Can be overwritten in the @productOptions field of each products.
  defaultProductsOptions: {
    Vendor: 'Stickerbull',
    Tags: 'custom-app-config',
    Published: 'true',
    'Option1 Name': 'Size',
    Status: 'active',
  },

  // Common options for all variants of all products.
  // These options will be added by default to all variants.
  // Can be overwritten in the @variantOptions field of each products.
  defaultVariantsOptions: {
    // 'Variant Inventory Qty': '10000',
    'Variant Inventory Policy': 'deny',
    'Variant Fulfillment Service': 'manual',
    'Variant Requires Shipping': 'true',
    'Variant Taxable': 'true',
    // 'Variant Grams': '0.0',
    'Variant Weight Unit': 'lb',
    // 'Cost per item': '0.10',
  },

  // Each block {} below represent a product to be generated in the final CSV.
  products: [
    /* DEFINITION :
     *
     * @title : String (Required) : The title of the product for Shopify.
     * @handleBase : String (Required) : The handle base of the product for Shopify. Must not contain spaces.
     *
     * @basePrice : Function () => {} (Required) : A function that takes a width and height argument and must return the base price of the variant.
     * It will be run on each variant.
     * Eg: If you return the following equation : (width * height * 0.10), you'll have the following result :
     * Variant 1x1 => (1 * 1 * 0.10) = $0.1 THEN Variant 1x2 => (1 * 2 * 0.10) = $0.2 ... THEN Variant 10x10 => (10 * 10 * 0.10) = $10 etc.
     * I've put 2 examples of basePrice functions for the first 2 products below. Tweak them at your convenience and then set the other ones.
     *
     * @sizeRange : Array of 2 strings ['', ''] (Required) : Size variants range from Min to Max for the product (in X in). Eg: ['1x1', '20x20'].
     * @productOptions : Object {} (Optional) : Options for the product. Eg: { 'Vendor': 'Stickermule', 'Tags': 'custom-config' }.
     * @variantsOptions : Object {} (Optional) : Options for each variant. Eg: { 'Variant Inventory Qty': '0', 'Variant SKU': 'SKU123', }.
     */

    {
      title: 'Custom Die Cut Stickers',
      handleBase: 'die-cut-stickers',
      sizeRange: ['1x1', '20x20'],
      basePrice: (width, height) => {
        const x = width * height
        const a = 4.09413
        const n = 0.819606
        const b = 47.1521
        const equation = a * x ** n + b
        const price = Math.round(equation) / 50 - 0.02
        return price - price * 0.1
      },
      productOptions: {
        'Product Type': 'holder-die-cut-stickers',
        'Image Src':
          'https://cdn.shopify.com/s/files/1/0637/7396/6592/files/DieCut_Sticker.png?v=1668475183',
        'Image Position': '1',
        'Image Alt Text': 'die cut sticker',
      },
      variantsOptions: {
        // 'Variant SKU': 'SKU123',
      },
    },
    {
      title: 'Custom Transparent Stickers',
      handleBase: 'transparent-stickers',
      sizeRange: ['1x1', '20x20'],
      basePrice: (width, height) => {
        const x = width * height
        const a = 4.09413
        const n = 0.819606
        const b = 47.1521
        const equation = a * x ** n + b
        const price = Math.round(equation) / 50 - 0.02
        return price - price * 0.1
      },
      productOptions: {
        'Product Type': 'holder-transparent-stickers',
        'Image Src':
          'https://cdn.shopify.com/s/files/1/0637/7396/6592/files/Clear_Sticker.png?v=1680451213',
        'Image Position': '1',
        'Image Alt Text': 'transparent sticker',
      },
      variantsOptions: {
        // 'Variant SKU': 'SKU456',
      },
    },
    {
      title: 'Custom Square/Rectangle Stickers',
      handleBase: 'square-rectangle-stickers',
      sizeRange: ['1x1', '20x20'],
      basePrice: (width, height) => {
        const x = width * height
        const a = 4.09413
        const n = 0.819606
        const b = 47.1521
        const equation = a * x ** n + b
        const price = Math.round(equation) / 50 - 0.02
        return price - price * 0.1
      },
      productOptions: {
        'Product Type': 'holder-square-rectangle-stickers',
        'Image Src':
          'https://cdn.shopify.com/s/files/1/0637/7396/6592/files/Rectangle_Sticker.png?v=1668453450',
        'Image Position': '1',
        'Image Alt Text': 'rectangle sticker',
      },
      variantsOptions: {
        // 'Variant SKU': 'SKU1045',
      },
    },
    {
      title: 'Custom Circle/Oval Stickers',
      handleBase: 'circle-oval-stickers',
      sizeRange: ['1x1', '20x20'],
      basePrice: (width, height) => {
        const x = width * height
        const a = 4.09413
        const n = 0.819606
        const b = 47.1521
        const equation = a * x ** n + b
        const price = Math.round(equation) / 50 - 0.02
        return price - price * 0.1
      },
      productOptions: {
        'Product Type': 'holder-circle-oval-stickers',
        'Image Src':
          'https://cdn.shopify.com/s/files/1/0637/7396/6592/files/Oval_Sticker.png?v=1668453437',
        'Image Position': '1',
        'Image Alt Text': 'circle sticker',
      },
      variantsOptions: {
        // 'Variant SKU': 'SKU895',
      },
    },
    {
      title: 'Custom Bumper Stickers',
      handleBase: 'bumper-stickers',
      sizeRange: ['1x1', '20x20'],
      basePrice: (width, height) => {
        const x = width * height
        const a = 4.09413
        const n = 0.819606
        const b = 47.1521
        const equation = a * x ** n + b
        const price = Math.round(equation) / 50 - 0.02
        return price - price * 0.1
      },
      productOptions: {
        'Product Type': 'holder-bumper-stickers',
        'Image Src':
          'https://cdn.shopify.com/s/files/1/0637/7396/6592/files/Bumper_Sticker.png?v=1680452539',
        'Image Position': '1',
        'Image Alt Text': 'bumper sticker',
      },
      variantsOptions: {
        // 'Variant SKU': 'SKU555',
      },
    },
    {
      title: 'Custom Kiss Cut Stickers',
      handleBase: 'kiss-cut-stickers',
      sizeRange: ['1x1', '20x20'],
      basePrice: (width, height) => {
        const x = width * height
        const a = 4.09413
        const n = 0.819606
        const b = 47.1521
        const equation = a * x ** n + b
        const price = Math.round(equation) / 50 - 0.02
        return price - price * 0.1
      },
      productOptions: {
        'Product Type': 'holder-kiss-cut-stickers',
        'Image Src':
          'https://cdn.shopify.com/s/files/1/0637/7396/6592/files/KissCut_Sticker.png?v=1680451828',
        'Image Position': '1',
        'Image Alt Text': 'kiss cut sticker',
      },
      variantsOptions: {
        // 'Variant SKU': 'SKU555',
      },
    },
    {
      title: 'Custom Die Cut Labels Roll',
      handleBase: 'die-cut-labels-roll',
      sizeRange: ['1x1', '20x20'],
      basePrice: (width, height) => {
        const x = width * height
        const a = 4.09413
        const n = 0.819606
        const b = 47.1521
        const equation = a * x ** n + b
        const price = Math.round(equation) / 50 - 0.02
        return price - price * 0.1
      },
      productOptions: {
        'Product Type': 'holder-die-cut-labels-roll',
        'Image Src':
          'https://cdn.shopify.com/s/files/1/0637/7396/6592/files/DieCut_Labels.png?v=1680453045',
        'Image Position': '1',
        'Image Alt Text': 'die cut labels roll',
      },
      variantsOptions: {
        // 'Variant SKU': 'SKU960',
      },
    },
    {
      title: 'Custom Square/Rectangle Labels Roll',
      handleBase: 'square-rectangle-labels-roll',
      sizeRange: ['1x1', '20x20'],
      basePrice: (width, height) => {
        const x = width * height
        const a = 4.09413
        const n = 0.819606
        const b = 47.1521
        const equation = a * x ** n + b
        const price = Math.round(equation) / 50 - 0.02
        return price - price * 0.1
      },
      productOptions: {
        'Product Type': 'holder-square-rectangle-labels-roll',
        'Image Src':
          'https://cdn.shopify.com/s/files/1/0637/7396/6592/files/Square_Labels.png?v=1680452818',
        'Image Position': '1',
        'Image Alt Text': 'square/rectangle labels roll',
      },
      variantsOptions: {
        // 'Variant SKU': 'SKU888',
      },
    },
    {
      title: 'Custom Circle/Oval Labels Roll',
      handleBase: 'circle-oval-labels-roll',
      sizeRange: ['1x1', '20x20'],
      basePrice: (width, height) => {
        const x = width * height
        const a = 4.09413
        const n = 0.819606
        const b = 47.1521
        const equation = a * x ** n + b
        const price = Math.round(equation) / 50 - 0.02
        return price - price * 0.1
      },
      productOptions: {
        'Product Type': 'holder-circle-oval-labels-roll',
        'Image Src':
          'https://cdn.shopify.com/s/files/1/0637/7396/6592/files/Circle_Labels.png?v=1680453634',
        'Image Position': '1',
        'Image Alt Text': 'circle/oval labels roll',
      },
      variantsOptions: {
        // 'Variant SKU': 'SKU888',
      },
    },
    {
      title: 'Custom Magnets',
      handleBase: 'magnets',
      sizeRange: ['1x1', '24x24'],
      basePrice: (width, height) => {
        const x = width * height
        const a = 4.09413
        const n = 0.819606
        const b = 47.1521
        const equation = a * x ** n + b
        const price = Math.round(equation) / 50 - 0.02
        return price - price * 0.1
      },
      productOptions: {
        'Product Type': 'holder-magnets',
        // 'Image Src':
      },
      variantsOptions: {
        // 'Variant SKU': 'SKU888',
      },
    },
  ],
}

module.exports = {
  CONFIG,
}
