/*
 * Open the link below for a complete description of the available fields from shopify  :
 * https://help.shopify.com/en/manual/products/import-export/using-csv#description-of-the-product-csv-file
 *
 * Please note that the 'Option[number] Name' and 'Option[value] Value' fields are generated by the script.
 * Don't set them yourself!
 *
 * AVAILABLE FIELDS FOR @productOptions :
 * 'Body (HTML)'
 * 'Vendor'
 * 'Product category'
 * 'Product Type'
 * 'Tags'
 * 'Published'
 * 'Image Src'
 * 'Image Position'
 * 'Image Alt Text'
 * 'Gift Card'
 * 'SEO Title'
 * 'SEO Description'
 * 'Google Shopping / Google Product Category'
 * 'Google Shopping / Gender'
 * 'Google Shopping / Age Group'
 * 'Google Shopping / MPN'
 * 'Google Shopping / AdWords Grouping'
 * 'Google Shopping / AdWords Labels'
 * 'Google Shopping / Condition'
 * 'Google Shopping / Custom Product'
 * 'Google Shopping / Custom Label 0'
 * 'Google Shopping / Custom Label 1'
 * 'Google Shopping / Custom Label 2'
 * 'Google Shopping / Custom Label 3'
 * 'Google Shopping / Custom Label 4'
 * 'Status'
 *
 *
 * AVAILABLE FIELDS FOR @variantsOptions :
 * 'Variant SKU'
 * 'Variant Grams'
 * 'Variant Inventory Tracker'
 * 'Variant Inventory Qty'
 * 'Variant Inventory Policy'
 * 'Variant Fulfillment Service'
 * 'Variant Price'
 * 'Variant Compare At Price'
 * 'Variant Requires Shipping'
 * 'Variant Taxable'
 * 'Variant Barcode'
 * 'Variant Image'
 * 'Variant Weight Unit'
 * 'Variant Tax Code'
 * 'Cost per item'
 *
 */

// CONFIG START HERE
const CONFIG = {
  // Common options for all products.
  // These options will be added by default to all products.
  // Can be overwritten in the @productOptions field of each products.
  defaultProductsOptions: {
    Vendor: 'StickerShuttle',
    'Product Type': 'config',
    Tags: 'custom-config',
    Published: 'true',
    'Option1 Name': 'Size',
    'Gift Card': 'false',
    Status: 'active',
  },

  // Common options for all variants of all products.
  // These options will be added by default to all variants.
  // Can be overwritten in the @variantOptions field of each products.
  defaultVariantsOptions: {
    'Variant Inventory Qty': '0',
    'Variant Inventory Policy': 'deny',
    'Variant Fulfillment Service': 'manual',
    'Variant Requires Shipping': 'true',
    'Variant Taxable': 'true',
    'Variant Grams': '0.0',
    'Variant Weight Unit': 'lb',
    'Cost per item': '0.10',
  },

  // Each block {} below represent a product to be generated in the final CSV.
  products: [
    /* DEFINITION :
     *
     * @title : String (Required) : The title of the product for Shopify.
     * @handleBase : String (Required) : The handle base of the product for Shopify. Must not contain spaces.
     *
     * @basePrice : Function () => {} (Required) : A function that takes a width and height argument and must return the base price of the variant.
     * It will be run on each variant.
     * Eg: If you return the following equation : (width * height * 0.10), you'll have the following result :
     * Variant 1x1 => (1 * 1 * 0.10) = $0.1 THEN Variant 1x2 => (1 * 2 * 0.10) = $0.2 ... THEN Variant 10x10 => (10 * 10 * 0.10) = $10 etc.
     * I've put 2 examples of basePrice functions for the first 2 products below. Tweak them at your convenience and then set the other ones.
     *
     * @sizeRange : Array of 2 strings ['', ''] (Required) : Size variants range from Min to Max for the product (in X in). Eg: ['1x1', '20x20'].
     * @productOptions : Object {} (Optional) : Options for the product. Eg: { 'Vendor': 'Stickermule', 'Tags': 'custom-config' }.
     * @variantsOptions : Object {} (Optional) : Options for each variant. Eg: { 'Variant Inventory Qty': '0', 'Variant SKU': 'SKU123', }.
     */

    // PRODUCT 1 START HERE
    {
      title: 'Custom Die-Cut Stickers',
      handleBase: 'custom-die-cut-stickers',
      sizeRange: ['1x1', '20x20'],
      basePrice: (width, height) => {
        const x = width * height
        const a = 4.09413
        const n = 0.819606
        const b = 47.1521
        const equation = a * x ** n + b
        return Math.round(equation) / 50 - 0.02
      },
      productOptions: {
        'Image Src':
          'https://cdn.shopify.com/s/files/1/0585/0546/1898/products/DieCut.png?v=1650732284',
        'Image Position': '1',
        'Image Alt Text': 'custom die-cut stickers',
      },
      variantsOptions: {
        'Variant SKU': 'SKU123',
      },
    },

    // PRODUCT 2 START HERE
    {
      title: 'Custom Circle/Oval Stickers',
      handleBase: 'custom-circle-oval-stickers',
      sizeRange: ['1x1', '20x20'],
      basePrice: (width, height) => {
        const x = width * height
        const a = 4.09413
        const n = 0.819606
        const b = 47.1521
        const equation = a * x ** n + b
        return Math.round(equation) / 50 - 0.02
      },
      productOptions: {
        'Image Src':
          'https://cdn.shopify.com/s/files/1/0585/0546/1898/files/Circle_c1071b32-0487-496c-abde-3358b11a1d21.png?v=1649343985',
        'Image Position': '1',
        'Image Alt Text': 'custom circle/oval stickers',
      },
      variantsOptions: {
        'Variant SKU': 'SKU456',
      },
    },

    // PRODUCT 3 START HERE
    {
      title: 'Custom Square Stickers',
      handleBase: 'custom-square-stickers',
      sizeRange: ['1x1', '20x20'],
      basePrice: (width, height) => {
        const x = width * height
        const a = 4.09413
        const n = 0.819606
        const b = 47.1521
        const equation = a * x ** n + b
        return Math.round(equation) / 50 - 0.02
      },
      productOptions: {
        'Image Src':
          'https://cdn.shopify.com/s/files/1/0585/0546/1898/files/Square.png?v=1649344004',
        'Image Position': '1',
        'Image Alt Text': 'custom square stickers',
      },
      variantsOptions: {
        'Variant SKU': 'SKU1045',
      },
    },

    // PRODUCT 4 START HERE
    {
      title: 'Custom Rectangle Stickers',
      handleBase: 'custom-rectangle-stickers',
      sizeRange: ['1x1', '20x20'],
      basePrice: (width, height) => {
        const x = width * height
        const a = 4.09413
        const n = 0.819606
        const b = 47.1521
        const equation = a * x ** n + b
        return Math.round(equation) / 50 - 0.02
      },
      productOptions: {
        'Image Src':
          'https://cdn.shopify.com/s/files/1/0585/0546/1898/files/Rectangle.png?v=1649344165',
        'Image Position': '1',
        'Image Alt Text': 'custom rectangle stickers',
      },
      variantsOptions: {
        'Variant SKU': 'SKU895',
      },
    },

    // PRODUCT 5 START HERE
    {
      title: 'Custom Bumper Stickers',
      handleBase: 'custom-bumper-stickers',
      sizeRange: ['1x1', '20x20'],
      basePrice: (width, height) => {
        const x = width * height
        const a = 4.09413
        const n = 0.819606
        const b = 47.1521
        const equation = a * x ** n + b
        return Math.round(equation) / 50 - 0.02
      },
      productOptions: {
        'Image Src':
          'https://cdn.shopify.com/s/files/1/0585/0546/1898/files/Bumper-Sticker_62405fcf-17d9-4f2e-a76a-157615976a16.png?v=1649345058',
        'Image Position': '1',
        'Image Alt Text': 'custom bumper stickers',
      },
      variantsOptions: {
        'Variant SKU': 'SKU555',
      },
    },

    // PRODUCT 6 START HERE
    {
      title: 'Custom Static Cling Stickers',
      handleBase: 'custom-static-cling-stickers',
      sizeRange: ['1x1', '20x20'],
      basePrice: (width, height) => {
        const x = width * height
        const a = 4.09413
        const n = 0.819606
        const b = 47.1521
        const equation = a * x ** n + b
        return Math.round(equation) / 50 - 0.02
      },
      productOptions: {
        'Image Src':
          'https://cdn.shopify.com/s/files/1/0585/0546/1898/files/static-cling.png?v=1649344936',
        'Image Position': '1',
        'Image Alt Text': 'custom static cling stickers',
      },
      variantsOptions: {
        'Variant SKU': 'SKU888',
      },
    },

    // PRODUCT 7 START HERE
    {
      title: 'Custom Clear Stickers',
      handleBase: 'custom-clear-stickers',
      sizeRange: ['1x1', '20x20'],
      basePrice: (width, height) => {
        const x = width * height
        const a = 4.09413
        const n = 0.819606
        const b = 47.1521
        const equation = a * x ** n + b
        return Math.round(equation) / 50 - 0.02
      },
      productOptions: {
        'Image Src':
          'https://cdn.shopify.com/s/files/1/0585/0546/1898/files/clear.png?v=1649344951',
        'Image Position': '1',
        'Image Alt Text': 'custom clear stickers',
      },
      variantsOptions: {
        'Variant SKU': 'SKU960',
      },
    },
  ],
}

module.exports = {
  CONFIG,
}
